# SPDX-FileCopyrightText: 2024-2025 Bryn Pickering <bp325@cam.ac.uk>
#
# SPDX-License-Identifier: CC0-1.0

default_language_version:
  python: python3

repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.14.1
  hooks:
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix]
  - id: ruff-format

- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
  - id: codespell
    args:
    - "--exclude-file=pixi.lock"
    - "--skip=*.csv"
    - '--ignore-words-list=Wirth'

- repo: https://github.com/fsfe/reuse-tool
  rev: v6.1.2
  hooks:
  - id: reuse-lint-file

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: debug-statements
  - id: check-yaml
    args: [--unsafe]
  - id: check-merge-conflict
  - id: check-illegal-windows-names
  - id: check-added-large-files
    args: [--enforce-all, --maxkb=10000]
  - id: trailing-whitespace
  - id: end-of-file-fixer


- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.15.0
  hooks:
  - id: pretty-format-yaml
    exclude: (\.lock\.yaml)$
    args: [--autofix, --indent, "2", --preserve-quotes]

ci: # https://pre-commit.ci/
  autofix_prs: false
  autoupdate_schedule: monthly
