# SPDX-FileCopyrightText: 2024-2025 Bryn Pickering <bp325@cam.ac.uk>
#
# SPDX-License-Identifier: CC-BY-4.0

[workspace]
authors = ["Bryn Pickering <17178478+brynpickering@users.noreply.github.com>"]
channels = ["conda-forge/label/calliope_dev", "conda-forge", "gurobi"]
name = "et-masterclass"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64", "linux-aarch64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
matplotlib = "3.9.2.*"
jupyterlab = "*"
gurobi = "11.0.*"
calliope = "0.7.0dev7.*"
click = ">=8.1"
pyproj = ">=3.6.1"
panel = ">=1.5.2,<1.6"
plotly = ">=5,<6"
pip = "*"
coin-or-cbc = ">=2.10.12,<3"
git = ">=2.51.1,<3"
pre-commit = ">=4.3.0,<5"

[pypi-dependencies]
calligraph = { git = "https://github.com/calliope-project/calligraph.git", rev = "v0.1.1.dev7" }
